apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: pod3
  annotations:
    "kubeshare/gpu_request": "0.5"
    "kubeshare/gpu_limit": "0.5"
    "kubeshare/gpu_mem": "3145728000"
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: tf
    image: guswns531/jobs:matrix-001
    command: ['./matrix', '2048', '2000']
  restartPolicy: OnFailure
