apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: pod4
  annotations:
    "kubeshare/gpu_request": "0.5"
    "kubeshare/gpu_limit": "0.5"
    "kubeshare/gpu_mem": "3145728000"
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: tf
    image: guswns531/jobs:matrix-002
    command: ['sleep', '4000']
    # command: ['LD_PRELOAD=/kubeshare/library/libgemhook.so.1', './matrix', '2048', '4000']
  restartPolicy: OnFailure
